### ISSUE TITLE
it can't edit fixer list from inspector

### ISSUE THREAD

**Issue by yhh1209** [AEspinosaDev/Cloth-Behaviour-Simulation#1]
I'm using unity 2022.1.23f1,.The clothes behaviour is working, but I can't edit (change list count or add elements for fixer list). How can I solve this bug?

**Comment by AEspinosaDev** [comment]
Hello @yhh1209 . Because of the last version of the plugin was made for an earlier version of Unity than yours, I don't have knowledge of the potential compatibility issues. Anyway, for what you tell me I can see the problem must be  ClothBehaviorEditor.cs file. Let me check it out and If I come with a solution I'll let you know.

Cheers.

**Comment by AEspinosaDev** [comment]
Hello again @yhh1209 . I've fixed the problem on my Unity newer version (2021.3.10f1), which also had the issue. I believe this will also fix your version, if not, please contact me again. I will commit the changes in the main branch in a moment and If I have the time, I may publish a new release. 

About the problem, apparently the newer versions of Unity require the serielizedObject List<> properties to be explicitly updated for a reason that for now I don't understand. Take a look at the image I sent you to see how to fix the issue.

![bug cloth](https://github.com/AEspinosaDev/Cloth-Behaviour-Simulation/assets/79087129/867717d4-7ff9-404d-ac64-c098c44b7033)

I also leave you a link for the documentation of the class that is giving the problems if you want to check it.
https://docs.unity3d.com/ScriptReference/SerializedObject.html

Please, contact me again if this modification solved your problem in order to close this issue.

**Comment by Javisda** [comment]
@AEspinosaDev Wow, I had the same issue and that worked for me. Thanks :D

**Comment by anomal3** [comment]
Probably the best fabric simulation I've ever seen and even github. Thank you very much

**Comment by TharHtetAungg** [comment]
Hello , where can I find the tutorial for this plug in ?
